import { proxyActivities, defineSignal, setHandler, condition } from '@temporalio/workflow';
import type * as activities from './activities';

const { remediateService, queryTelemetry, hypothesize, generateProposal, verifyRemediation } = proxyActivities<typeof activities>({
  startToCloseTimeout: '1 minute',
});

// We'll pass the approval object, including the hash, to verify it hasn't mutated
export const approveActionSignal = defineSignal<[{ approved: boolean, proposalHash: string }]>('approveAction');
import { defineQuery } from '@temporalio/workflow';
export const getProposalQuery = defineQuery<{ action: string, proposalHash: string, hypothesis: string } | null>('getProposal');

export async function incidentResponseWorkflow(incidentId: string, serviceUrl: string): Promise<string> {
  let activeProposal: { action: string, proposalHash: string, hypothesis: string } | null = null;
  setHandler(getProposalQuery, () => activeProposal);
  // Investigation
  const metricQuery = `rate(checkout_errors_total[1m])`;
  const queryResult = await queryTelemetry(metricQuery);
  const hypothesis = await hypothesize(queryResult);
  
  // Create a proposal (using actual hash generated by activity)
  const { action, proposalHash } = await generateProposal(hypothesis, serviceUrl);
  activeProposal = { action, proposalHash, hypothesis };
  console.log(`Action Proposed: ${action}. Hash: ${proposalHash}. Hypothesis: ${hypothesis}`);

  let approvalData: { approved: boolean, proposalHash: string } | null = null;
  setHandler(approveActionSignal, (data) => {
    approvalData = data;
  });

  // Wait for human approval, or timeout after 10 minutes
  const isApproved = await condition(() => approvalData !== null, '10m');

  if (!isApproved) {
    return `Incident ${incidentId} escalated: Approval timed out after 10 minutes.`;
  }

  if (approvalData!.proposalHash !== proposalHash) {
    return `Incident ${incidentId} rejected: Stale or invalid proposal hash.`;
  }

  if (approvalData!.approved) {
    const result = await remediateService(serviceUrl);
    const verified = await verifyRemediation(serviceUrl, metricQuery);
    if (!verified) {
       return `Incident ${incidentId} verification FAILED: ${result}. Error rates did not normalize.`;
    }
    return `Incident ${incidentId} resolved: ${result}. Verified: ${verified}. Hypothesis was: ${hypothesis}`;
  } else {
    return `Incident ${incidentId} resolution was rejected by operator.`;
  }
}
