import { proxyActivities, defineSignal, setHandler, condition } from '@temporalio/workflow';
import type * as activities from './activities';

const { remediateService, queryTelemetry, hypothesize, generateProposal, verifyRemediation } = proxyActivities<typeof activities>({
  startToCloseTimeout: '1 minute',
});

// We'll pass the approval object, including the hash, to verify it hasn't mutated
export const approveActionSignal = defineSignal<[{ approved: boolean, proposalHash: string, approver: string }]>('approveAction');
import { defineQuery } from '@temporalio/workflow';
export const getProposalQuery = defineQuery<{ action: string, proposalHash: string, hypothesis: string } | null>('getProposal');

export async function incidentResponseWorkflow(incidentId: string, serviceUrl: string): Promise<any> {
  let activeProposal: { action: string, proposalHash: string, hypothesis: string } | null = null;
  setHandler(getProposalQuery, () => activeProposal);
  // Investigation
  let targetService = 'checkout';
  if (serviceUrl.includes('5002')) targetService = 'payments';
  if (serviceUrl.includes('5003')) targetService = 'inventory';
  
  const metricQuery = `rate(${targetService}_errors_total[20s])`;
  const queryResult = await queryTelemetry(metricQuery);
  const hypothesis = await hypothesize(queryResult);
  
  // Create a proposal (using actual hash generated by activity)
  const { action, proposalHash } = await generateProposal(incidentId, hypothesis, serviceUrl);
  activeProposal = { action, proposalHash, hypothesis };
  console.log(`Action Proposed: ${action}. Hash: ${proposalHash}. Hypothesis: ${hypothesis}`);

  let approvalData: { approved: boolean, proposalHash: string, approver: string } | null = null;
  setHandler(approveActionSignal, (data) => {
    approvalData = data;
  });

  // Wait for human approval, or timeout after 10 minutes
  const isApproved = await condition(() => approvalData !== null, '10m');

  if (!isApproved) {
    return { outcome: 'escalated', verification: 'none', message: `Incident ${incidentId} escalated: Approval timed out after 10 minutes.` };
  }

  if (approvalData!.proposalHash !== proposalHash) {
    return { outcome: 'rejected', verification: 'none', message: `Incident ${incidentId} rejected: Stale or invalid proposal hash.` };
  }

  if (!approvalData!.approver || approvalData!.approver.trim() === '') {
    return { outcome: 'rejected', verification: 'none', message: `Incident ${incidentId} rejected: Missing authenticated approver.` };
  }

  if (approvalData!.approved) {
    const result = await remediateService(serviceUrl);
    const verification = await verifyRemediation(serviceUrl, metricQuery);
    if (verification.status === 'inconclusive') {
       return { outcome: 'inconclusive', verification: 'inconclusive', evidenceIds: verification.metrics, message: `Incident ${incidentId} verification INCONCLUSIVE: ${result}. Missing telemetry prevents confirmation.` };
    }
    if (verification.status === 'failed') {
       return { outcome: 'failed', verification: 'failed', evidenceIds: verification.metrics, message: `Incident ${incidentId} verification FAILED: ${result}. Error rates did not normalize or traffic is too low.` };
    }
    return { outcome: 'recovered', verification: 'success', evidenceIds: verification.metrics, message: `Incident ${incidentId} resolved: ${result}. Verified: ${verification.status}. Hypothesis was: ${hypothesis}` };
  } else {
    return { outcome: 'rejected', verification: 'none', message: `Incident ${incidentId} resolution was rejected by operator.` };
  }
}
